/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_facture_client (void);
GtkWidget* create_modifier (void);
GtkWidget* create_supprimer_fact (void);
GtkWidget* create_ajouter (void);
